import api from './api';

export const submitEnquiry = (payload) => api.post('/enquiries', payload);
export const login = (payload) => api.post('/auth/login', payload);
export const me = () => api.get('/auth/me');
export const logout = () => api.post('/auth/logout');
export const getDashboardSummary = () => api.get('/dashboard/summary');
export const getTrend = () => api.get('/dashboard/enquiries-trend');
export const getStatusSummary = () => api.get('/dashboard/status-summary');
export const getTypeSummary = () => api.get('/dashboard/type-summary');
export const getProductSummary = () => api.get('/dashboard/product-summary');
export const getMonthlyTrend = () => api.get('/dashboard/monthly-trend');
export const listEnquiries = (params) => api.get('/enquiries', { params });
export const getEnquiry = (id) => api.get(`/enquiries/${id}`);
export const updateEnquiry = (id, payload) => api.put(`/enquiries/${id}`, payload);
export const changeStatus = (id, payload) => api.patch(`/enquiries/${id}/status`, payload);
export const assignEnquiry = (id, payload) => api.patch(`/enquiries/${id}/assign`, payload);
export const addRemark = (id, payload) => api.post(`/enquiries/${id}/remarks`, payload);
export const listCustomers = (params) => api.get('/customers', { params });
export const getCustomer = (id) => api.get(`/customers/${id}`);
export const listFollowups = (params) => api.get('/followups', { params });
export const createFollowup = (payload) => api.post('/followups', payload);
export const updateFollowupStatus = (id, payload) => api.patch(`/followups/${id}/status`, payload);
export const getReport = (params) => api.get('/reports/enquiries', { params });
export const getConversion = (params) => api.get('/reports/conversion', { params });
export const listUsers = () => api.get('/users');
export const listAssignableUsers = () => api.get('/users/assignable');
export const createUser = (payload) => api.post('/users', payload);
export const updateUser = (id, payload) => api.put(`/users/${id}`, payload);
export const setUserStatus = (id, payload) => api.patch(`/users/${id}/status`, payload);
export const listWhatsapp = (params) => api.get('/whatsapp', { params });
export const sendWhatsapp = (payload) => api.post('/whatsapp/send', payload);
export const retryWhatsapp = (id) => api.post(`/whatsapp/${id}/retry`);
export const listAudit = (params) => api.get('/audit-logs', { params });
export const getSettings = () => api.get('/settings');
export const updateSettings = (payload) => api.put('/settings', payload);
export const downloadConfirmation = (enquiryId) =>
  api.get(`/confirmations/enquiry/${enquiryId}/download`, { responseType: 'blob' });
export const getFormOptions = () => api.get('/form-options');
